version: "3.8"

services:
  piano:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python server/run_server.py
    container_name: playbook-piano
    image: playbook/piano:local
    ports:
      - "20019:20019"
    volumes:
      - .:/app
